steps:
  # - name: 'gcr.io/cloud-builders/mvn'
  #   args: ['install']
  - name: "gcr.io/$PROJECT_ID/sonar-scanner:latest" 
    args: [ 
      "-Dsonar.projectKey=celestialsahil_cloudbuild-clouddeploy", 
      "-Dsonar.sources=.", 
      "-Dsonar.host.url=https://sonarcloud.io", 
      "-Dsonar.login=${_SONAR_TOKEN}",
      "-Dsonar.java.binaries=.",
      "-Dsonar.qualitygate.wait=true" ]
substitutions:
  _SONAR_TOKEN: "044993e76b3572f8b6941a6d9a23a6904bfc964e"
